# Generated by Django 5.0.6 on 2024-05-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(max_length=50)),
                ('note', models.CharField(max_length=1000)),
                ('diagnose', models.CharField(max_length=100)),
                ('photo_before', models.ImageField(upload_to='')),
                ('photo_after', models.ImageField(upload_to='')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
