# Generated by Django 5.0.6 on 2024-05-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_diagnose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='PPatient',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UUser',
        ),
        migrations.DeleteModel(
            name='Diagnose',
        ),
    ]
