# Generated by Django 5.0.6 on 2024-05-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_patient_ppatient_rename_user_uuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('note', models.CharField(max_length=1000)),
                ('diagnose', models.CharField(max_length=100)),
                ('photo_before', models.ImageField(upload_to='')),
                ('photo_after', models.ImageField(upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ppatient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uuser')),
            ],
        ),
    ]
